name: ecocycle
description: A  Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  path_provider: ^2.0.5
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.6.0
  flutter_signin_button: ^2.0.0
  shared_preferences: ^2.0.8
  google_fonts: ^4.0.4
  provider: ^6.0.1
  firebase_core_platform_interface: ^4.5.1
  intl: ^0.17.0

  


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  url_launcher: ^6.0.10

flutter_native_splash: 
  android: true
  web: true 
  color: "ffffff"
  image: assets/images/splashh.png


flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 700

  uses-material-design: true

  
  assets:
    - assets/images/market_image.png
    - assets/images/profile_image.png
    - assets/images/info_image.png
    - assets/images/farm_academy_image.png
    - assets/images/splashh.png
    - assets/images/splash22.png
    - assets/images/your_image.png
    - assets/images/leaf.png
    - assets/images/apple.png
    - assets/images/bread.png
    - assets/images/onion.png
